const data = {
  products: [
    {
      name: 'Diary',
      slug: 'diary',
      category: 'Read',
      image: '/images/z_pants1.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled diary',
    },
    {
      name: 'File',
      slug: 'file',
      category: 'Write',
      image: '/images/z_pants2.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled file',
    },
    {
      name: 'Notebook',
      slug: 'notebook',
      category: 'read',
      image: '/images/z_pants3.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled notebook',
    },
    {
      name: 'Notepad',
      slug: 'notepad',
      category: 'Read',
      image: '/images/z_shirt1.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled notepad',
    },
    {
      name: 'Pen',
      slug: 'pen',
      category: 'Write',
      image: '/images/z_shirt2.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled pen',
    },
    {
      name: 'Pencil',
      slug: 'pencil',
      category: 'Write',
      image: '/images/z_shirt3.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled pencil',
    },
    // {
    //   name: 'SeedPen',
    //   slug: 'seedPen',
    //   category: 'Write',
    //   image: '/images/seedPen.jpeg',
    //   brand: 'REcosystem',
    //   rating: '5',
    //   numReviews: 8,
    //   countInStock: 20,
    //   description: 'A recycled seed pen',
    // }
  ],
};

export default data;
