import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Diary',
      slug: 'diary',
      category: 'Read',
      image: '/images/z_pants1.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled diary',
      price: 100,
    },
    {
      name: 'File',
      slug: 'file',
      category: 'Write',
      image: '/images/z_pants2.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled file',
      price: 100,
    },
    {
      name: 'Notebook',
      slug: 'notebook',
      category: 'read',
      image: '/images/z_pants3.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled notebook',
      price: 100,
    },
    {
      name: 'Notepad',
      slug: 'notepad',
      category: 'Read',
      image: '/images/z_shirt1.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled notepad',
      price: 100,
    },
    {
      name: 'Pen',
      slug: 'pen',
      category: 'Write',
      image: '/images/z_shirt2.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled pen',
      price: 100,
    },
    {
      name: 'Pencil',
      slug: 'pencil',
      category: 'Write',
      image: '/images/z_shirt3.jpg',
      brand: 'REcosystem',
      rating: '5',
      numReviews: 8,
      countInStock: 20,
      description: 'A recycled pencil',
      price: 100,
    },
    // {
    //   name: 'SeedPen',
    //   slug: 'seedPen',
    //   category: 'Write',
    //   image: '/images/seedPen.jpeg',
    //   brand: 'REcosystem',
    //   rating: '5',
    //   numReviews: 8,
    //   countInStock: 20,
    //   description: 'A recycled seed pen',
    //   price: 100
    // }
  ],
};

export default data;
